Initial conversion from Rnw to Rmd
Bioconductor/GSEABase pull request #6
Opened 2022-09-06 18:24 UTC by villafup

@Bioconductor/sweave2rmd The original has a line break in the **_package_** section of the yaml.  I couldn't get it to work, so I added it as a sidenote.  Do any of you know how to put a line break here?  Wasn't able to google anything useful.

### **_Original_**
![Original](https://user-images.githubusercontent.com/95894130/188709914-873acf05-d0a7-47a1-9a62-e0421833f45f.png)

### **_Converted_**
![Converted](https://user-images.githubusercontent.com/95894130/188709913-44629aae-e112-4847-841d-b086e4dce6f2.png)

2022-09-06 20:46 UTC, mtmorgan commented
I think these commits should remove the original Rnw file (else R CMD build will not necessarily do what is expected) and should add the translator to the DESCRIPTION file as a contributor with comment about translating vignettes from Rnw to Rmd. Perhaps this would involve changes to the `Authors@R` format.

2022-12-01 04:06 UTC, jwokaty requested changes
In addition to the inline requested, the .Rnw should be removed as Martin suggested then I believe we can resolve the conflict and merge.

2022-12-01 04:06 UTC, jwokaty commented on DESCRIPTION
> +        comment= comment = "'GSEABase' vignette translation from Sweave to Rmarkdown / HTML")
Fix "role" on line 8.

2022-12-01 04:06 UTC, jwokaty commented on DESCRIPTION
>          <maintainer@bioconductor.org>
This line should be removed and we should add to the `Authors@R` vector a `person` entry for the `Bioconductor Package Maintainer` as in https://github.com/Bioconductor/graph/blob/7522c5c9bf227067bd02bc76f7ef7668b77baa68/DESCRIPTION#L12-L15. This is a consequence of using the `Authors@R`; otherwise, we'll get an error when building the package.

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +package: GSEABase 1.59.0^[Report issues on https://github.com/Bioconductor/GSEABase/issues]
The version should be updated to the current devel version, 1.61.0. This was likely created before the release, but we'll always merge with devel (it's less work). I'll deal with the conflict this generates with the `DESCRIPTION` file before merging.

I think the footnote doesn't work here because it's the YAML part of the document. We can do the following that will look similar to the PDF:

```
package: |
  GSEABase 1.59.0

  Report issues on https://github.com/Bioconductor/GSEABase/issues
```

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +    toc: yes
`yes` should be `true`. I made an issue in sweave2rmd to correct this misinfo.

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +To construct a gene set, use `GeneSet` . For example, to create a gene set from
Remove space between `GeneSet` and period.

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +The identifier type of gene sets created from expression sets is .
Missing the name "AnnotationIdentifier" before the period.

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +containing an arbitrary map. Use the `verbose`argument of `mapIdentifiers` to be informed when the
Need space after `verbose`

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +band 24 of the q arm of chromosome 16. The probe sets in chip
Insert `hgu95av2` after "chip".

2022-12-01 04:06 UTC, jwokaty commented on vignettes/GSEABase.Rmd
> +expression set, and is not necessarily 1:1.
This section lost a few words. It should read

```
Remember that `sample.ExpressionSet` contains just 500 probe sets, so the small size of the
subset is not surprising. Note also that subsetting required mapping of symbol identifiers in
bgs to AnnotationIdentifiers; this map used the annotation information in the expression set,
and is not necessarily 1:1.
```

2023-02-24 19:45 UTC, jwokaty commented
- [ ] the `.Rmd` file knits to `HTML`
- [ ] `R CMD build` runs without errors or timeouts
- [ ] the tarball from `R CMD build` contains the `HTML` (check with the
  following by substituting the package name and vignette name `tar ztf
  package_name.tar.gz | grep 'doc/vignette_name'`)
- [ ] the `.Rnw` file has been removed
- [ ] in the `DESCRIPTION`, `BiocStyle` and `knitr` are listed in `Suggests`
- [ ] in the `DESCRIPITON`, the line `VignetteBuilder: knitr` exists
- [ ] any added lines use the same spacing and indents as the existing
  document
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the `DESCRIPTION` file; refer to the contribution guide for acceptable
  formats
- [ ] if agreed with the Maintainer, the contributor is in the author list
  in the vignette's YAML; refer to the contribution guide for acceptable formats
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, check that the
  `Authors@R` vector includes the maintainer as specified with `role='cre'`.
- [ ] if this pull request includes a conversion from using the separate `Author`
  and `Maintainer` lines into the `Authors@R` vector, the `Maintainer` line
  is completely removed.
- [ ] `HTML` document is representative of the `PDF` in content and
  in general the presentation
- [ ] Where the contributor was not able to preserve the content and presentation
  of the `PDF` is noted as a comment in the pull request
- [ ] the R Markdown file is representative of the Sweave document and follows
  best practices, such as replacing links to Bioconductor packages with calls
  to BiocStyle's `Biocpkg()`

2023-02-24 21:10 UTC, merged

2023-02-25 21:40 UTC, mtmorgan commented
FWIW, as a further sanity check I created the R script that is implied by the Rnw vignette (before applying the PR)
```
R CMD Stangle vignettes/GSEABase.Rnw
mv GSEABase.R GSEABase-Rnw.R
```
and after the PR
```
R CMD Stangle vignettes/GSEABase.Rmd
mv GSEABase.R GSEABase-Rmd.R
```
Then I compared the two files, ignoring spaces
```
$ diff -w GSEABase-Rmd.R GSEABase-Rnw.R
0a1,4
> ## ----style-knitr, eval=TRUE, echo=FALSE, results="asis"-----------------------
> BiocStyle::latex()
>
>
62d65
<
124d126
<
151c153
< ## ----ReportingTools, echo=TRUE------------------------------------------------
---
> ## ----ReportingTools-----------------------------------------------------------
$
```
Manually inspecting this, I see that there are NO MEANINGFUL CHANGES in the evaluated R code.

This is great, thanks so much for this translation!

2023-02-27 18:47 UTC, jwokaty commented
> FWIW, as a further sanity check I created the R script that is implied by the Rnw vignette (before applying the PR)
> 
> ```
> R CMD Stangle vignettes/GSEABase.Rnw
> mv GSEABase.R GSEABase-Rnw.R
> ```
> 
> and after the PR
> 
> ```
> R CMD Stangle vignettes/GSEABase.Rmd
> mv GSEABase.R GSEABase-Rmd.R
> ```
> 
> Then I compared the two files, ignoring spaces
> 
> ```
> $ diff -w GSEABase-Rmd.R GSEABase-Rnw.R
> 0a1,4
> > ## ----style-knitr, eval=TRUE, echo=FALSE, results="asis"-----------------------
> > BiocStyle::latex()
> >
> >
> 62d65
> <
> 124d126
> <
> 151c153
> < ## ----ReportingTools, echo=TRUE------------------------------------------------
> ---
> > ## ----ReportingTools-----------------------------------------------------------
> $
> ```
> 
> Manually inspecting this, I see that there are NO MEANINGFUL CHANGES in the evaluated R code.
> 
> This is great, thanks so much for this translation!

@mtmorgan Thanks for sharing this. I've been thinking a lot about how we can automate and improve the process since it's very manual and requires careful attention to detail. I never used `Stangle` and I think this is a great tool for sweave2rmd.